# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28b544f0fd7c26d9e28f1bc808b3c302a94cfd217d7baafbff98c6c2a8ed26fcb8e46af4ec760aadaa0963f094404e521c5c56f32a576dcded28fe47585808ad

test:
  secret_key_base: 6d31fd389b640d46af3053802058c2c375fea45d6f656fd951653d72c7e5ca85c688a6add36e6dc995568008d70af4f9822aca8fc93cd54a31151ff2e6a29653

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
